webtalk_init -webtalk_dir C:\\Users\\Mustafa\\Desktop\\Xfighter\\Xfighter.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "fr jan. 20 17:25:40 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6sm84216vda1p5rt7l8nkc91c9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_21" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1484928873616" -context "sdk\\\\bsp/1484928873616"
webtalk_add_data -client sdk -key hwid -value "1484313707094" -context "sdk\\\\bsp/1484928873616"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1484928873616"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1484928873616"
webtalk_add_data -client sdk -key uid -value "1484928880402" -context "sdk\\\\application/1484928880402"
webtalk_add_data -client sdk -key hwid -value "1484313707094" -context "sdk\\\\application/1484928880402"
webtalk_add_data -client sdk -key bspid -value "1484928873616" -context "sdk\\\\application/1484928880402"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1484928880402"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1484928880402"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1484928880402"
webtalk_transmit -clientid 1552153955 -regid "" -xml C:\\Users\\Mustafa\\Desktop\\Xfighter\\Xfighter.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Users\\Mustafa\\Desktop\\Xfighter\\Xfighter.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Users\\Mustafa\\Desktop\\Xfighter\\Xfighter.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
